#!/bin/sh -e

BUILD_TYPE=${BUILD_TYPE:-RelWithDebInfo}

if [ -r /etc/os-release ]
then
	. /etc/os-release
fi

if [ "${ID}" = "steamrt" ]
then
	# Already inside the runtime, as in the sdk container or on ci
	exec bin/steamrt/${BUILD_TYPE}/tests "$@"
else
	exec ~/.steam/steam/steamapps/common/SteamLinuxRuntime_4/run --share-pid -- \
	    bin/steamrt/${BUILD_TYPE}/tests "$@"
fi
