#!/bin/sh -e

cmd/steamrt/build || true

inotifywait -r -e CLOSE_WRITE -m shibe tests deps | \
    while read path action file
	do
		clear
		echo "Rebuilding"
		cmd/steamrt/build && cmd/steamrt/run || true
		echo "Done"
    done
